## PEDIDOS ORIGEM SISTEMA CONECTA
## 26.05.2022

pedidosv2 <- dbGetQuery(con2,"
  
  WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),
  
  SETOR AS (SELECT ZOCODIGO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,28)),
  
  ENDE AS (SELECT ENDCODIGO,CLICODIGO FROM ENDCLI INNER JOIN SETOR ON ENDCLI.ZOCODIGO=SETOR.ZOCODIGO WHERE ENDFAT='S'),
  
  PEDEMIS AS (SELECT ID_PEDIDO,PEDDTEMIS,PEDDTBAIXA,PEDID.CLICODIGO,POCCODIGO FROM PEDID INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
   INNER JOIN ENDE ON PEDID.CLICODIGO=ENDE.CLICODIGO AND PEDID.ENDCODIGO=ENDE.ENDCODIGO
    WHERE PEDDTEMIS BETWEEN '01.04.2022' AND 'YESTERDAY' AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N')
    AND POCCODIGO=101)
  
  
  SELECT PD.ID_PEDIDO,PEDDTEMIS,PEDDTBAIXA,CLICODIGO,PROCODIGO,PDPDESCRICAO,POCCODIGO,SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
   FROM PDPRD PD
    INNER JOIN PEDEMIS ON PD.ID_PEDIDO=PEDEMIS.ID_PEDIDO
  GROUP BY 1,2,3,4,5,6,7
  ")  


View(pedidosv2)

pedidosv2 %>% select(CLICODIGO) %>% distinct()

