## Bibliotecas necessárias

library(DBI)
library(dplyr)


## conexão com banco replica 

con2 <- dbConnect(odbc::odbc(), "reproreplica")



library(tidyverse)

#CURRENT MONTH

pedidosv1 <- dbGetQuery(con2,"

WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),

SETOR AS (SELECT ZOCODIGO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,28)),

ENDE AS (SELECT ENDCODIGO,CLICODIGO FROM ENDCLI INNER JOIN SETOR ON ENDCLI.ZOCODIGO=SETOR.ZOCODIGO WHERE ENDFAT='S'),

PEDEMIS AS (SELECT ID_PEDIDO,PEDID.CLICODIGO FROM PEDID INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
 INNER JOIN ENDE ON PEDID.CLICODIGO=ENDE.CLICODIGO AND PEDID.ENDCODIGO=ENDE.ENDCODIGO
  WHERE PEDDTEMIS BETWEEN '01.04.2022' AND 'YESTERDAY' AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))


SELECT PD.ID_PEDIDO,CLICODIGO,PROCODIGO,PDPDESCRICAO,SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
 FROM PDPRD PD
  INNER JOIN PEDEMIS ON PD.ID_PEDIDO=PEDEMIS.ID_PEDIDO
GROUP BY 1,2,3,4
")  


View(pedidosv1)

# verifica pedidos que contem um produto

inner_join(pedidosv1 %>% filter(str_detect(PROCODIGO,"LP0026")) %>% select(ID_PEDIDO),
           pedidosv1,by='ID_PEDIDO') %>% View()